name: dp
description: A flutter db util
version: 0.0.3
homepage: http://github.com/huhuang03
author: th <huhuang03@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'


dependencies:
  path: ^1.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
